// Technical articles (VI/EN). Drafts written from widely known practices; NAK should review before promoting.
// Block types: { h } heading, { p } paragraph, { ul: [] } list.
module.exports = [
  {
    slug: 'sao-luu-3-2-1-va-ransomware', date: '2026-10-03', minutes: 5, solution: 'storage', photo: 'datacenter',
    vi: {
      title: 'Sao lưu 3-2-1: lớp bảo vệ cuối cùng trước mã độc tống tiền',
      excerpt: 'Khi hệ thống bị tấn công, bản sao lưu đáng tin cậy thường là khác biệt giữa vài giờ khôi phục và vài tuần gián đoạn. Quy tắc 3-2-1 là điểm khởi đầu đơn giản và hiệu quả.',
      body: [
        { p: 'Một vụ rò rỉ dữ liệu có thể rất tốn kém. Theo báo cáo IBM Cost of a Data Breach 2025, chi phí trung bình toàn cầu của một vụ rò rỉ là 4,44 triệu USD, và các sự cố tống tiền hoặc ransomware có chi phí trung bình cao hơn, khoảng 5,08 triệu USD. Phần lớn thiệt hại đến từ thời gian ngừng hoạt động và công sức khôi phục.' },
        { h: 'Quy tắc 3-2-1 là gì?' },
        { ul: ['3 bản dữ liệu: bản gốc và ít nhất hai bản sao lưu.', '2 loại phương tiện lưu trữ khác nhau, ví dụ hệ thống lưu trữ và băng từ hoặc cloud.', '1 bản đặt ở nơi khác, tách biệt với địa điểm chính.'] },
        { h: 'Vì sao ransomware làm quy tắc này quan trọng hơn?' },
        { p: 'Mã độc tống tiền thường tìm và mã hóa cả các bản sao lưu có thể truy cập từ mạng chính. Vì vậy, nhiều tổ chức bổ sung nguyên tắc về tính bất biến (immutable) hoặc tách rời (air-gapped): ít nhất một bản sao lưu không thể bị sửa hoặc xóa từ hệ thống đang vận hành.' },
        { h: 'Những sai lầm thường gặp' },
        { ul: ['Có sao lưu nhưng chưa bao giờ thử khôi phục.', 'Để bản sao lưu cùng mạng và cùng tài khoản quản trị với hệ thống chính.', 'Không xác định mục tiêu thời gian khôi phục (RTO) và mức mất dữ liệu chấp nhận được (RPO).', 'Chỉ sao lưu máy chủ mà bỏ qua email, cấu hình thiết bị mạng và dữ liệu SaaS.'] },
        { h: 'Bắt đầu từ đâu?' },
        { p: 'Liệt kê hệ thống quan trọng, xác định RTO và RPO cho từng hệ thống, áp dụng 3-2-1 với ít nhất một bản bất biến, và đặt lịch kiểm thử khôi phục định kỳ. Một buổi đánh giá hiện trạng thường đủ để thấy các khoảng trống lớn nhất.' },
      ],
      sources: [{ t: 'IBM Cost of a Data Breach Report 2025 (qua Help Net Security)', u: 'https://www.helpnetsecurity.com/2025/08/04/ibm-cost-data-breach-report-2025/' }],
    },
    en: {
      title: 'The 3-2-1 backup rule: your last line of defence against ransomware',
      excerpt: 'When systems are attacked, a trustworthy backup is often the difference between hours of recovery and weeks of disruption. The 3-2-1 rule is a simple, effective starting point.',
      body: [
        { p: 'A data breach can be very costly. According to IBM’s Cost of a Data Breach Report 2025, the global average cost of a breach is US$4.44 million, and extortion or ransomware incidents average higher, around US$5.08 million. Much of the damage comes from downtime and recovery effort.' },
        { h: 'What is the 3-2-1 rule?' },
        { ul: ['3 copies of data: the original and at least two backups.', '2 different storage media, for example a storage system and tape or cloud.', '1 copy kept off-site, separate from the primary location.'] },
        { h: 'Why ransomware makes the rule more important' },
        { p: 'Ransomware often finds and encrypts backups that are reachable from the main network. Many organizations therefore add immutability or air-gapping: at least one backup copy that cannot be modified or deleted from the running environment.' },
        { h: 'Common mistakes' },
        { ul: ['Having backups but never testing a restore.', 'Keeping backups on the same network and admin account as production.', 'Not defining a recovery time objective (RTO) and acceptable data loss (RPO).', 'Backing up servers but ignoring email, network device configs and SaaS data.'] },
        { h: 'Where to start' },
        { p: 'List critical systems, define RTO and RPO for each, apply 3-2-1 with at least one immutable copy, and schedule regular restore tests. A single assessment session is usually enough to reveal the biggest gaps.' },
      ],
      sources: [{ t: 'IBM Cost of a Data Breach Report 2025 (via Help Net Security)', u: 'https://www.helpnetsecurity.com/2025/08/04/ibm-cost-data-breach-report-2025/' }],
    },
  },
  {
    slug: 'hybrid-cloud-khi-nao-giu-tai-cho-khi-nao-len-aws', date: '2026-10-03', minutes: 5, solution: 'aws', photo: 'glass',
    vi: {
      title: 'Hybrid cloud: khi nào giữ hệ thống tại chỗ, khi nào đưa lên AWS',
      excerpt: 'Không phải hệ thống nào cũng nên lên cloud, và cũng không nên giữ mọi thứ tại chỗ. Một khung quyết định đơn giản giúp chọn đúng nơi cho từng khối lượng công việc.',
      body: [
        { p: 'Gartner dự báo 90% tổ chức sẽ áp dụng cách tiếp cận hybrid cloud đến hết năm 2027, và chi tiêu public cloud toàn cầu dự kiến đạt 723,4 tỷ USD trong năm 2025. Hybrid đang dần là mặc định thay vì ngoại lệ.' },
        { h: 'Những hệ thống thường phù hợp để lên cloud' },
        { ul: ['Ứng dụng có tải biến động theo mùa hoặc theo chiến dịch.', 'Môi trường phát triển và kiểm thử, cần tạo và hủy nhanh.', 'Sao lưu ngoài địa điểm và khôi phục thảm họa.', 'Ứng dụng mới cần ra thị trường nhanh.'] },
        { h: 'Những hệ thống thường nên giữ tại chỗ' },
        { ul: ['Hệ thống đòi hỏi độ trễ rất thấp với thiết bị tại nhà máy.', 'Dữ liệu chịu ràng buộc nghiêm ngặt về nơi lưu trữ hoặc tuân thủ.', 'Khối lượng công việc ổn định, dự đoán được và đã tối ưu về chi phí tại chỗ.'] },
        { h: 'Bốn câu hỏi để quyết định' },
        { ul: ['Tải của hệ thống có biến động nhiều không?', 'Dữ liệu có bị ràng buộc về vị trí hoặc quy định không?', 'Độ trễ tối đa chấp nhận được là bao nhiêu?', 'Tổng chi phí 3 đến 5 năm ở mỗi phương án là bao nhiêu?'] },
        { h: 'Đừng quên kết nối và quản trị' },
        { p: 'Hybrid thành công cần kết nối mạng ổn định giữa trung tâm dữ liệu và cloud, định danh thống nhất, giám sát chung và kiểm soát chi phí từ đầu. Đây thường là phần bị đánh giá thấp nhất khi lập kế hoạch.' },
      ],
      sources: [
        { t: 'Gartner dự báo hybrid cloud 90% đến 2027 (qua VARindia)', u: 'https://www.varindia.com/news/gartner-predicts-90-of-organizations-to-be-adopting-hybrid-cloud-through-2027' },
        { t: 'Gartner: chi tiêu public cloud 2025', u: 'https://www.gartner.com/en/newsroom/press-releases/2024-11-19-gartner-forecasts-worldwide-public-cloud-end-user-spending-to-total-723-billion-dollars-in-2025' },
      ],
    },
    en: {
      title: 'Hybrid cloud: when to keep systems on-premises and when to move to AWS',
      excerpt: 'Not every system belongs in the cloud, and not everything should stay on-premises. A simple decision framework helps place each workload in the right home.',
      body: [
        { p: 'Gartner forecasts that 90% of organizations will adopt a hybrid cloud approach through 2027, and worldwide public cloud spending is projected at US$723.4 billion in 2025. Hybrid is becoming the default rather than the exception.' },
        { h: 'Systems that often suit the cloud' },
        { ul: ['Applications with seasonal or campaign-driven load.', 'Development and test environments that need to be created and destroyed quickly.', 'Off-site backup and disaster recovery.', 'New applications that need fast time to market.'] },
        { h: 'Systems that often stay on-premises' },
        { ul: ['Systems needing very low latency to devices on the plant floor.', 'Data with strict location or compliance constraints.', 'Stable, predictable workloads already cost-optimized on-premises.'] },
        { h: 'Four questions to decide' },
        { ul: ['Does the workload vary a lot?', 'Is the data bound by location or regulation?', 'What is the maximum acceptable latency?', 'What is the 3 to 5 year total cost for each option?'] },
        { h: 'Do not forget connectivity and governance' },
        { p: 'Successful hybrid needs stable connectivity between data center and cloud, unified identity, shared monitoring and cost control from day one. This is usually the most underestimated part of planning.' },
      ],
      sources: [
        { t: 'Gartner hybrid cloud 90% through 2027 forecast (via VARindia)', u: 'https://www.varindia.com/news/gartner-predicts-90-of-organizations-to-be-adopting-hybrid-cloud-through-2027' },
        { t: 'Gartner: 2025 public cloud spending forecast', u: 'https://www.gartner.com/en/newsroom/press-releases/2024-11-19-gartner-forecasts-worldwide-public-cloud-end-user-spending-to-total-723-billion-dollars-in-2025' },
      ],
    },
  },
  {
    slug: 'checklist-ha-tang-mang-cho-nha-may-va-van-phong-moi', date: '2026-10-03', minutes: 4, solution: 'network', photo: 'network',
    vi: {
      title: 'Checklist hạ tầng mạng cho nhà máy và văn phòng mới',
      excerpt: 'Mạng được thiết kế đúng ngay từ đầu tiết kiệm nhiều chi phí chỉnh sửa về sau. Danh sách kiểm tra này tóm tắt những điểm cần chốt trước khi triển khai.',
      body: [
        { p: 'Dù là một văn phòng mới hay nâng cấp mạng nhà máy, các quyết định ở giai đoạn thiết kế ảnh hưởng đến hiệu năng, an ninh và chi phí vận hành nhiều năm sau đó. Dưới đây là những nhóm câu hỏi nên trả lời sớm.' },
        { h: '1. Yêu cầu và quy mô' },
        { ul: ['Số lượng người dùng và thiết bị hiện tại, và dự kiến sau 3 đến 5 năm.', 'Các ứng dụng quan trọng và yêu cầu băng thông, độ trễ của chúng.', 'Thiết bị đặc thù: máy sản xuất, camera, IoT, thiết bị y tế.'] },
        { h: '2. Cáp và mặt bằng' },
        { ul: ['Sơ đồ đi cáp, tủ rack, phòng thiết bị và nguồn điện dự phòng.', 'Khảo sát Wi-Fi mặt bằng để xác định vị trí và số lượng điểm phát.', 'Dự phòng cổng và đường cáp cho nhu cầu mở rộng.'] },
        { h: '3. Phân vùng và an ninh' },
        { ul: ['Tách mạng người dùng, máy chủ, khách và thiết bị sản xuất hoặc IoT thành các vùng riêng.', 'Tường lửa và chính sách giữa các vùng.', 'Kiểm soát truy cập thiết bị và xác thực người dùng.'] },
        { h: '4. Dự phòng và đường truyền' },
        { ul: ['Hai đường Internet từ hai nhà cung cấp cho hệ thống quan trọng.', 'Thiết bị lõi dự phòng và nguồn điện UPS.', 'Kế hoạch khi một liên kết hoặc thiết bị hỏng.'] },
        { h: '5. Vận hành và tài liệu' },
        { ul: ['Giám sát và cảnh báo thiết bị mạng.', 'Sao lưu cấu hình và quy trình thay đổi có kiểm soát.', 'Bàn giao sơ đồ mạng, bảng địa chỉ IP và tài liệu cấu hình.'] },
      ],
      sources: [],
    },
    en: {
      title: 'A network infrastructure checklist for a new plant or office',
      excerpt: 'A network designed right from the start saves a lot of rework later. This checklist summarizes the points to settle before deployment.',
      body: [
        { p: 'Whether it is a new office or a plant network upgrade, decisions made at design time affect performance, security and operating cost for years. Here are the groups of questions to answer early.' },
        { h: '1. Requirements and scale' },
        { ul: ['Current and expected users and devices over 3 to 5 years.', 'Critical applications and their bandwidth and latency needs.', 'Special devices: production machines, cameras, IoT, medical equipment.'] },
        { h: '2. Cabling and floor plan' },
        { ul: ['Cable routes, racks, equipment room and backup power.', 'A Wi-Fi site survey to set access-point positions and count.', 'Spare ports and pathways for growth.'] },
        { h: '3. Segmentation and security' },
        { ul: ['Separate user, server, guest and production or IoT networks into distinct zones.', 'Firewall and policy between zones.', 'Device access control and user authentication.'] },
        { h: '4. Redundancy and uplinks' },
        { ul: ['Two Internet links from two providers for critical systems.', 'Redundant core devices and UPS power.', 'A plan for when a link or device fails.'] },
        { h: '5. Operations and documentation' },
        { ul: ['Monitoring and alerting for network devices.', 'Configuration backup and controlled change process.', 'Handover of network diagrams, IP address tables and configuration documents.'] },
      ],
      sources: [],
    },
  },
];
